### ISSUE TITLE
Components (capital letter vs. role attribute)

### ISSUE THREAD

**Issue by adamthebig** [picdorsey/frunt#5]
This is probably silly to re-hash this, but the capital letter is bugging me. It just seems out of place.

What if we used attributes and defined our own role?

**Something like:**

``` html
<div class="slideshow" role="component">
```

I don't think the prefix is required. It is really just so we can identify components in the HTML.

Thoughts?

**Comment by tylerodonnell** [comment]
I personally like the capital letter but I'm not married to the convention. I'll use whatever everyone else likes.

The one advantage using a capital letter is that it _forces_ you to stick to that convention due to the fact CSS is case sensitive.

I think the big advantage of using attributes is that they provide cues that an item is a component without muddying up the HTML and CSS. Everything still looks and behaves like css always has.

**Comment by adamthebig** [comment]
All good points. I've just spent so many years with lowercase and dashes, it's hard to get used to. It beats the 'c-' for sure.

Also, attributes would allow us to programmatically identify or parse components (if we ever needed to) for testing or reporting or just a hook for JS.
